In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'U:\unified mentorship\project 2\Nassau Candy Distributor.csv')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [3]:
df1=df.copy()
df1.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.5,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.5,2,4.90,2.60

**Feature Engineering**

*Calculate Shipping Lead Time (days)*

In [4]:
df1['Order Date']=pd.to_datetime(df1['Order Date'],format='%d-%m-%Y')
df1['Ship Date']=pd.to_datetime(df1['Ship Date'],format='%d-%m-%Y')
df1.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00

In [70]:
df1['Shipping Lead Time']=df1['Ship Date']-df1['Order Date']
df1.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Customer Region Route,Customer State Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909 days,United States->Interior,Interior->Texas
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909 days,United States->Interior,Interior->Illinois
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909 days,United States->Interior,Interior->Illinois

In [6]:
print(df1['Region'].unique())
print()
print(df1['State/Province'].unique())

['Interior' 'Atlantic' 'Gulf' 'Pacific']

['Texas' 'Illinois' 'Pennsylvania' 'Kentucky' 'Georgia' 'California'
 'Virginia' 'Delaware' 'South Carolina' 'Ohio' 'Louisiana' 'Oregon'
 'Arizona' 'Arkansas' 'Michigan' 'Tennessee' 'Florida' 'Ontario' 'Indiana'
 'Nevada' 'South Dakota' 'New York' 'Wisconsin' 'Washington' 'New Jersey'
 'Missouri' 'North Carolina' 'Colorado' 'Alberta' 'Utah' 'Minnesota'
 'Mississippi' 'Iowa' 'New Mexico' 'Massachusetts' 'Alabama' 'Idaho'
 'Montana' 'Maryland' 'Connecticut' 'New Hampshire' 'British Columbia'
 'Quebec' 'Nova Scotia' 'Oklahoma' 'Nebraska' 'Maine' 'Kansas'
 'Rhode Island' 'Newfoundland and Labrador' 'New Brunswick'
 'Prince Edward Island' 'District of Columbia' 'Vermont' 'Manitoba'
 'Saskatchewan' 'Wyoming' 'North Dakota' 'West Virginia']

*Categorize routes*

In [7]:
df1['Customer Region Route']=df1['Country/Region']+'->'+df1['Region']
df1['Customer State Route']=df1['Region']+'->'+ df1['State/Province']
df1.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Customer Region Route,Customer State Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909 days,United States->Interior,Interior->Texas
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909 days,United States->Interior,Interior->Illinois
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909 days,United States->Interior,Interior->Illinois

Which route has highest sales?
Which region has longest shipping lead time?
Which ship mode performs best in each region?
Which state gets most delayed shipments?

In [8]:
#Q-1>
df1.groupby('Customer Region Route')['Sales'].sum().sort_values(ascending=False)

Customer Region Route
United States->Pacific     45451.06
United States->Atlantic    39232.67
United States->Interior    31899.35
United States->Gulf        22247.26
Canada->Atlantic            1964.57
Canada->Pacific              850.47
Canada->Interior             138.25
Name: Sales, dtype: float64

In [9]:
#Q-2>
df1.groupby('Customer Region Route')['Shipping Lead Time'].sum().sort_values(ascending=False)

Customer Region Route
United States->Interior     82898 days 05:56:08.066277376
Canada->Pacific                       64427 days 00:00:00
Canada->Interior                      17464 days 00:00:00
United States->Gulf       -10613 days +04:14:22.904483840
United States->Pacific    -33407 days +08:28:45.808967680
Canada->Atlantic          -37417 days +00:25:26.290448384
United States->Atlantic   -69442 days +07:37:53.228070912
Name: Shipping Lead Time, dtype: timedelta64[ns]

In [10]:
#Q-3>
df1.groupby('Ship Mode').agg({
    'Sales': ['sum', 'mean'],
    'Gross Profit':['max','mean'],
    'Shipping Lead Time': 'min'
})

                   Sales            Gross Profit           Shipping Lead Time
                     sum       mean          max      mean                min
Ship Mode
First Class     21319.39  13.772216         90.0  9.051092           905 days
Same Day         7113.67  13.004881         40.0  8.593656           904 days
Second Class    27860.22  14.077928        130.0  9.250389           906 days
Standard Class  85490.35  13.969011        110.0  9.219683           908 days

In [11]:
#Q-4>
df1.groupby(['State/Province'])['Shipping Lead Time'].sum().sort_values(ascending=False).head(1)

State/Province
Missouri   88431 days
Name: Shipping Lead Time, dtype: timedelta64[ns]

In [12]:
df1.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Customer Region Route,Customer State Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.5,2,4.22,2.28,909 days,United States->Interior,Interior->Texas
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.5,2,4.90,2.60,909 days,United States->Interior,Interior->Illinois

*Group shipments by Ship Mode*

In [13]:
print(df1.groupby('Ship Mode').size())
print()
print(df1.groupby('Ship Mode')['Shipping Lead Time'].mean())

Ship Mode
First Class       1548
Same Day           547
Second Class      1979
Standard Class    6120
dtype: int64

Ship Mode
First Class      1338 days 06:37:12.558139536
Same Day         1333 days 10:37:04.497257776
Second Class     1323 days 20:17:20.525517936
Standard Class   1314 days 08:01:52.941176464
Name: Shipping Lead Time, dtype: timedelta64[ns]

In [14]:
df1.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Customer Region Route,Customer State Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.5,2,4.22,2.28,909 days,United States->Interior,Interior->Texas

**Route Definition & Aggregation**

In [15]:
Customer_Region_Route_Analysis = df1.groupby('Customer Region Route').agg(
    Total_Shipment= ('Order ID'            , 'count'),
Average_Time_Lead=  ('Shipping Lead Time'  , 'mean'),
Lead_Time_Vriablity=('Shipping Lead Time'  , 'std')
)
Customer_Region_Route_Analysis

,Total_Shipment,Average_Time_Lead,Lead_Time_Vriablity
Customer Region Route,,,
Canada->Atlantic,138,1275 days 23:49:33.913043472,291 days 02:14:12.040131684
Canada->Interior,12,1455 days 08:00:00,191 days 03:21:18.968248660
Canada->Pacific,50,1288 days 12:57:36,295 days 00:05:56.894353596
United States->Atlantic,2848,1325 days 00:15:10.112359552,254 days 14:07:10.918498184
United States->Gulf,1620,1311 days 08:59:33.333333328,264 days 17:28:06.683556984
United States->Interior,2323,1322 days 09:47:39.233749456,262 days 20:52:48.158964536
United States->Pacific,3203,1322 days 17:17:10.658757408,266 days 00:26:07.674568384

**Efficiency Benchmarking**

In [16]:
r_10_last_efficient_routes=df1.groupby('Customer State Route')['Shipping Lead Time'].mean().sort_values(ascending=False).head(10)
r_10_last_efficient_routes

Customer State Route
Atlantic->West Virginia                    1638 days 00:00:00
Interior->North Dakota           1637 days 20:34:17.142857136
Pacific->Saskatchewan                      1457 days 00:00:00
Interior->Manitoba                         1455 days 08:00:00
Interior->Iowa                             1443 days 21:36:00
Pacific->New Mexico              1441 days 20:06:29.189189184
Atlantic->Vermont                1438 days 21:49:05.454545456
Atlantic->Prince Edward Island             1420 days 07:12:00
Interior->South Dakota                     1395 days 22:00:00
Gulf->Tennessee                  1391 days 11:40:19.672131152
Name: Shipping Lead Time, dtype: timedelta64[ns]

In [17]:
r_10_most_efficient_routes=df1.groupby('Customer State Route')['Shipping Lead Time'].mean().sort_values(ascending=False).tail(10)
r_10_most_efficient_routes

Customer State Route
Pacific->Oregon                       1267 days 17:01:56.129032256
Gulf->Mississippi                     1266 days 13:35:05.660377360
Gulf->Louisiana                       1263 days 18:51:25.714285712
Gulf->South Carolina                  1255 days 10:17:08.571428576
Pacific->Utah                                   1253 days 00:00:00
Atlantic->Ontario                     1247 days 11:10:20.689655168
Gulf->Virginia                                  1229 days 03:00:00
Pacific->Nevada                       1226 days 19:04:36.923076928
Atlantic->Newfoundland and Labrador             1216 days 04:00:00
Atlantic->Maine                                 1137 days 03:00:00
Name: Shipping Lead Time, dtype: timedelta64[ns]

In [18]:
df1.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Customer Region Route,Customer State Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.5,2,4.22,2.28,909 days,United States->Interior,Interior->Texas

In [19]:
df1.groupby('Ship Mode').agg({
    'Sales':['max','mean'],
    'Units':['sum'],
    'Gross Profit':['mean']
})

                Sales             Units Gross Profit
                  max       mean    sum         mean
Ship Mode
First Class     180.0  13.772216   5724     9.051092
Same Day         80.0  13.004881   1975     8.593656
Second Class    260.0  14.077928   7546     9.250389
Standard Class  220.0  13.969011  23409     9.219683

**Geographic Bottleneck Analysis**

In [20]:
df1.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Customer Region Route,Customer State Route
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.5,2,4.22,2.28,909 days,United States->Interior,Interior->Texas

In [21]:
df1.groupby('Region')['Shipping Lead Time'].mean().sort_values(ascending=False).head(1)

Region
Interior   1323 days 02:11:21.456102784
Name: Shipping Lead Time, dtype: timedelta64[ns]

*High shipment volume + poor performance*

In [29]:
df1['Region'].value_counts().sort_values(ascending=False)

Region
Pacific     3253
Atlantic    2986
Interior    2335
Gulf        1620
Name: count, dtype: int64

In [30]:
pacific_region=df1[df1['Region']=='Pacific']
pacific_region.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Customer Region Route,Customer State Route
11,12,US-2021-130813-CHO-MIL-31000,2024-01-06,2026-07-01,Second Class,130813,United States,Los Angeles,California,90049,...,Pacific,CHO-MIL-31000,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42,907 days,United States->Pacific,Pacific->California

In [53]:
region_perf=df1.groupby('Region').agg(
    Total_Shipment= ('Order ID', 'count'),
    Sales=('Sales','sum'),
    Units=('Units','sum'),
    Gross_Profit=('Gross Profit','sum'),
    Average_Time_Lead=('Shipping Lead Time'  , 'mean'),
    Lead_Time_Vriablity=('Shipping Lead Time'  , 'std')
)
region_perf

,Total_Shipment,Sales,Units,Gross_Profit,Average_Time_Lead,Lead_Time_Vriablity
Region,,,,,,
Atlantic,2986,41197.24,11159,26973.70,1322 days 17:53:00.442062960,256 days 13:00:12.368459748
Gulf,1620,22247.26,6209,14700.67,1311 days 08:59:33.333333328,264 days 17:28:06.683556984
Interior,2335,32037.60,8820,21282.49,1323 days 02:11:21.456102784,262 days 16:38:46.816608564
Pacific,3253,46301.53,12466,30485.94,1322 days 04:40:39.102367040,266 days 11:17:43.933598604

In [62]:
print(region_perf.sort_values('Total_Shipment',ascending=False))
print()
print()
print(region_perf.sort_values('Average_Time_Lead',ascending=False))

          Total_Shipment     Sales  Units  Gross_Profit  \
Region
Pacific             3253  46301.53  12466      30485.94
Atlantic            2986  41197.24  11159      26973.70
Interior            2335  32037.60   8820      21282.49
Gulf                1620  22247.26   6209      14700.67

                    Average_Time_Lead         Lead_Time_Vriablity
Region
Pacific  1322 days 04:40:39.102367040 266 days 11:17:43.933598604
Atlantic 1322 days 17:53:00.442062960 256 days 13:00:12.368459748
Interior 1323 days 02:11:21.456102784 262 days 16:38:46.816608564
Gulf     1311 days 08:59:33.333333328 264 days 17:28:06.683556984


          Total_Shipment     Sales  Units  Gross_Profit  \
Region
Interior            2335  32037.60   8820      21282.49
Atlantic            2986  41197.24  11159      26973.70
Pacific             3253  46301.53  12466      30485.94
Gulf                1620  22247.26   6209      14700.67

                    Average_Time_Lead         Lead_Time_Vriablity
Region
Interior 1323 days 02:11:21.456102784 262 days 16:38:46.816608564
Atlantic 1322 days 17:53:00.442062960 256 days 13:00:12.368459748
Pacific  1322 days 04:40:39.102367040 266 days 11:17:43.933598604
Gulf     1311 days 08:59:33.333333328 264 days 17:28:06.683556984

In [58]:
df1['Shipping Lead Time'].corr(df1['Gross Profit']) # no relation hence i have to define perfomance on shipment and lead time only

np.float64(-0.003305492046526824)

In [66]:
region_perf.sort_values(
    ['Total_Shipment'],
    ascending=[False]
)

,Total_Shipment,Sales,Units,Gross_Profit,Average_Time_Lead,Lead_Time_Vriablity
Region,,,,,,
Pacific,3253,46301.53,12466,30485.94,1322 days 04:40:39.102367040,266 days 11:17:43.933598604
Atlantic,2986,41197.24,11159,26973.70,1322 days 17:53:00.442062960,256 days 13:00:12.368459748
Interior,2335,32037.60,8820,21282.49,1323 days 02:11:21.456102784,262 days 16:38:46.816608564
Gulf,1620,22247.26,6209,14700.67,1311 days 08:59:33.333333328,264 days 17:28:06.683556984

*Detect congestion-prone states or regions*

In [ ]:
#Regional shipping performance appears relatively consistent across all regions. Despite
#differences in shipment volume, average lead times range
#only from 1311 to 1323 days and lead-time variability remains similar (256–266 days).

**Ship Mode Performance Analysis**